# Generated by Django 5.2.6 on 2025-09-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('photo', models.ImageField(upload_to='show/')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.TimeField()),
                ('places', models.IntegerField()),
            ],
        ),
    ]
