# Generated by Django 5.2.6 on 2025-09-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='show/'),
        ),
    ]
