# Generated by Django 5.2.6 on 2025-10-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_show_places_typeticket_ticket'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('type', 'row', 'place'), name='unique_seat_per_type'),
        ),
    ]
