# Generated by Django 5.2.6 on 2025-10-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_ticket_unique_seat_per_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_seat_per_type',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='type',
            new_name='type_ticket',
        ),
        migrations.RenameField(
            model_name='typeticket',
            old_name='type',
            new_name='type_ticket',
        ),
        migrations.AddField(
            model_name='galery',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='typeticket',
            unique_together={('show', 'type_ticket')},
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('type_ticket', 'row', 'place'), name='unique_seat_per_type'),
        ),
    ]
