# Generated by Django 5.2.6 on 2025-10-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_ticket_unique_seat_per_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='adress',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
